# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trade Me Jobs Unofficial ExpressJs Client
email: amir(dot)mohtasebi(at)gmail(dot)com
description: > # this means to ignore newlines until "baseurl:"
  Unofficial expressjs client for Trade Me Jobs API.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mohtasebi.com" # the base hostname & protocol for your site
twitter_username: amirmohtasebi
github_username:  wizact

# Build settings
markdown: kramdown

 lsi: false
 safe: true
 source: tmj-cli
 incremental: false
 highlighter: rouge
 gist:
   noscript: false
 kramdown:
   math_engine: mathjax